/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jonesx_audioplayer_AudioPlayer */

#ifndef _Included_jonesx_audioplayer_AudioPlayer
#define _Included_jonesx_audioplayer_AudioPlayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jonesx_audioplayer_AudioPlayer
 * Method:    play
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jonesx_audioplayer_AudioPlayer_play
  (JNIEnv *, jclass);

/*
 * Class:     jonesx_audioplayer_AudioPlayer
 * Method:    stop
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jonesx_audioplayer_AudioPlayer_stop
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
